# Generated by Django 2.0.2 on 2018-04-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='videos html url')),
                ('content', models.TextField(verbose_name='content')),
                ('phone', models.IntegerField(verbose_name='phone')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
            ],
        ),
    ]
